SELECT
  S_SUPPKEY
FROM (
  SELECT
    S_SUPPKEY,
    SUM(L_EXTENDEDPRICE * (
      1 - L_DISCOUNT
    )) AS REVENUE,
    RANK() OVER (ORDER BY SUM(L_EXTENDEDPRICE * (
      1 - L_DISCOUNT
    )) DESC) AS RANK_NUM
  FROM SUPPLIER
  JOIN LINEITEM
    ON S_SUPPKEY = L_SUPPKEY
  WHERE
    L_SHIPDATE >= DATE '1997-01-01'
    AND L_SHIPDATE < DATE '1997-01-01' + INTERVAL '3 month'
  GROUP BY
    S_SUPPKEY
) AS RANKED_SUPPLIERS
WHERE
  RANK_NUM = 1
ORDER BY
  S_SUPPKEY;