SELECT
    N.N_NAME,
    EXTRACT(YEAR FROM L.L_SHIPDATE) AS YEAR,
    SUM(L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT) - PS.PS_SUPPLYCOST * L.L_QUANTITY) AS PROFIT
FROM
    NATION N,
    SUPPLIER S,
    PART P,
    PARTSUPP PS,
    LINEITEM L
WHERE
    P.P_PARTKEY = PS.PS_PARTKEY
    AND S.S_SUPPKEY = PS.PS_SUPPKEY
    AND L.L_PARTKEY = PS.PS_PARTKEY
    AND L.L_SUPPKEY = PS.PS_SUPPKEY
    AND S.S_NATIONKEY = N.N_NATIONKEY
    AND P.P_NAME LIKE '%red%'
GROUP BY
    N.N_NAME,
    YEAR
ORDER BY
    N.N_NAME ASC,
    YEAR DESC;